use anyhow::{Context, Result};
use std::collections::{BTreeSet, HashMap};
use std::path::Path;
use tokio::fs::File;
use tokio::io::{AsyncWriteExt, BufWriter};
use tracing::info;

use super::models::*;
use super::utils::ensure_directory_exists;

pub struct CodeGenerator;

impl CodeGenerator {
    pub fn new() -> Self {
        Self
    }
    
    pub async fn generate<P: AsRef<Path>>(
        &self,
        mnemonics: &BTreeSet<Mnemonic>,
        opcode_maps: &OpcodeMaps,
        output_path: P,
    ) -> Result<()> {
        let output_path = output_path.as_ref();
        ensure_directory_exists(output_path).await?;
        
        let file = File::create(output_path)
            .await
            .with_context(|| format!("Failed to create file: {}", output_path.display()))?;
        
        let mut writer = BufWriter::new(file);
        
        self.write_header(&mut writer).await?;
        self.write_mnemonic_enum(mnemonics, &mut writer).await?;
        self.write_as_str_method(mnemonics, &mut writer).await?;
        self.write_single_byte_resolver(&opcode_maps.single_byte, &mut writer).await?;
        self.write_prefixed_0f_resolver(&opcode_maps.prefixed_0f, &mut writer).await?;
        self.write_flag_effects_stub(&mut writer).await?;
        
        writer.flush().await?;
        
        info!("Generated: {}", output_path.display());
        
        Ok(())
    }
    
    async fn write_header(&self, writer: &mut BufWriter<File>) -> Result<()> {
        writer.write_all(b"// AUTO-GENERATED by scripts/isa_generator\n").await?;
        writer.write_all(b"// DO NOT EDIT THIS FILE DIRECTLY\n").await?;
        writer.write_all(b"// Source: Go Arch x86.csv\n").await?;
        writer.write_all(b"\n").await?;
        Ok(())
    }
    
    async fn write_mnemonic_enum(&self, mnemonics: &BTreeSet<Mnemonic>, writer: &mut BufWriter<File>) -> Result<()> {
        writer.write_all(b"#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n").await?;
        writer.write_all(b"pub enum AutoMnemonic {\n").await?;
        
        let mut counter = 0u32;
        for mnemonic in mnemonics {
            let variant = mnemonic.as_variant();
            writer.write_all(format!("    {} = {},\n", variant, counter).as_bytes()).await?;
            counter += 1;
        }
        
        writer.write_all(b"    Unknown,\n").await?;
        writer.write_all(b"}\n\n").await?;
        Ok(())
    }
    
    async fn write_as_str_method(&self, mnemonics: &BTreeSet<Mnemonic>, writer: &mut BufWriter<File>) -> Result<()> {
        writer.write_all(b"impl AutoMnemonic {\n").await?;
        writer.write_all(b"    #[must_use]\n").await?;
        writer.write_all(b"    pub const fn as_str(&self) -> &'static str {\n").await?;
        writer.write_all(b"        match self {\n").await?;
        
        for mnemonic in mnemonics {
            let variant = mnemonic.as_variant();
            let lower = mnemonic.0.to_lowercase();
            writer.write_all(format!("            AutoMnemonic::{} => \"{}\",\n", variant, lower).as_bytes()).await?;
        }
        
        writer.write_all(b"            AutoMnemonic::Unknown => \"??\",\n").await?;
        writer.write_all(b"        }\n").await?;
        writer.write_all(b"    }\n").await?;
        writer.write_all(b"}\n\n").await?;
        Ok(())
    }
    
    async fn write_single_byte_resolver(&self, opcode_map: &HashMap<u8, String>, writer: &mut BufWriter<File>) -> Result<()> {
        writer.write_all(b"pub fn auto_resolve_opcode(opcode: u8) -> AutoMnemonic {\n").await?;
        writer.write_all(b"    match opcode {\n").await?;
        
        let mut keys: Vec<u8> = opcode_map.keys().copied().collect();
        keys.sort_unstable();
        
        for op in keys {
            let mnemonic = &opcode_map[&op];
            writer.write_all(format!("        0x{:02X} => AutoMnemonic::{},\n", op, mnemonic).as_bytes()).await?;
        }
        
        writer.write_all(b"        _ => AutoMnemonic::Unknown,\n").await?;
        writer.write_all(b"    }\n").await?;
        writer.write_all(b"}\n\n").await?;
        Ok(())
    }
    
    async fn write_prefixed_0f_resolver(&self, opcode_map: &HashMap<u8, String>, writer: &mut BufWriter<File>) -> Result<()> {
        writer.write_all(b"pub fn auto_resolve_opcode_0f(opcode: u8) -> AutoMnemonic {\n").await?;
        writer.write_all(b"    match opcode {\n").await?;
        
        let mut keys: Vec<u8> = opcode_map.keys().copied().collect();
        keys.sort_unstable();
        
        for op in keys {
            let mnemonic = &opcode_map[&op];
            writer.write_all(format!("        0x{:02X} => AutoMnemonic::{},\n", op, mnemonic).as_bytes()).await?;
        }
        
        writer.write_all(b"        _ => AutoMnemonic::Unknown,\n").await?;
        writer.write_all(b"    }\n").await?;
        writer.write_all(b"}\n\n").await?;
        Ok(())
    }
    
    async fn write_flag_effects_stub(&self, writer: &mut BufWriter<File>) -> Result<()> {
        writer.write_all(b"pub fn auto_flag_effects(mnemonic: AutoMnemonic) -> u32 {\n").await?;
        writer.write_all(b"    match mnemonic {\n").await?;
        writer.write_all(b"        AutoMnemonic::Unknown => 0,\n").await?;
        writer.write_all(b"        _ => 1,\n").await?;
        writer.write_all(b"    }\n").await?;
        writer.write_all(b"}\n").await?;
        Ok(())
    }
}