/*
** ISA specification and semantic metadata definitions.
** This work is dedicated to the public domain under CC0 1.0 Universal.
*/

/*
** Instruction represents a fully decoded x86/x64 instruction.
** It contains the raw bytes, prefixes, and high-level semantic
** information required for static analysis.
*/
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Instruction {
    /* The virtual address where the instruction is located. */
    pub address: u64,
    /* The full sequence of bytes forming the instruction. */
    pub bytes: Vec<u8>,
    /* The legacy and REX prefixes detected during decoding. */
    pub prefixes: Vec<u8>,
    /* The primary instruction mnemonic. */
    pub mnemonic: Mnemonic,
    /* Explicit, implicit, and hidden operands. */
    pub operands: Vec<Operand>,
    /* Architecture-specific classification and flag effects. */
    pub metadata: InstructionMetadata,
    /* Detailed breakdown of the instruction's byte segments. */
    pub segments: InstructionSegments,
}

/*
** InstructionSegments identifies the byte offsets and lengths of each
** structural component of the instruction.
*/
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct InstructionSegments {
    pub prefixes: SegmentInfo,
    pub opcode: SegmentInfo,
    pub modrm: SegmentInfo,
    pub sib: SegmentInfo,
    pub displacement: SegmentInfo,
    pub immediate: SegmentInfo,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct SegmentInfo {
    pub offset: u8,
    pub length: u8,
}

use crate::autogen_isa::AutoMnemonic;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Mnemonic {
    Add, Sub, Mov, Push, Pop, Ret, Call, Jmp, Nop, Syscall,
    Cmp, Xor, And, Or, Adc, Sbb,
    Jz, Jnz, Js, Jns, Jo, Jno, Jb, Jae,
    Lea, Int,
    Test, Inc, Dec,
    Pushfq, Popfq,
    Clc, Stc, Cld, Std,
    Vmovaps, Vaddps, Vsubps,
    Aesenc, Aesdec,
    Movs,
    Ldtilecfg, Sttilecfg, Tdpbf16ps,
    Vprotb, // XOP example
    Fadd, Fsub, Fmul, Fdiv, // x87 examples
    Endbr64, // CET example
    Xadd, Cmpxchg, Neg, Not, Btc, Btr, Bts, Xchg,
    Unknown,
    Auto(AutoMnemonic), // Autogenerated mapping integration
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Operand {
    Register {
        reg: Register,
        access: AccessType,
        visibility: Visibility,
        /* AVX-512 Opmask applied to this destination register (e.g. {k1}) */
        opmask: Option<Register>, 
        /* AVX-512 Zeroing behavior on inactive elements ({z}) */
        zeroing: bool,
    },
    Immediate {
        imm: Immediate,
        visibility: Visibility,
    },
    Memory {
        mem: MemoryAccess,
        access: AccessType,
        visibility: Visibility,
        opmask: Option<Register>,
        zeroing: bool,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Visibility {
    /* Operand is explicitly encoded in the instruction bytes. */
    Explicit,
    /* Operand is part of the instruction semantics but not encoded. */
    Implicit,
    /* Operand is used internally and not usually shown in disassembly. */
    Hidden,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AccessType {
    Read,
    Write,
    ReadWrite,
    None,
}

/*
** Register definitions for x86 and x86_64.
*/
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Register {
    /* 64-bit GPRs */
    Rax, Rcx, Rdx, Rbx, Rsp, Rbp, Rsi, Rdi,
    R8,  R9,  R10, R11, R12, R13, R14, R15,
    R16, R17, R18, R19, R20, R21, R22, R23,
    R24, R25, R26, R27, R28, R29, R30, R31,

    /* 32-bit GPRs */
    Eax, Ecx, Edx, Ebx, Esp, Ebp, Esi, Edi,
    R8d, R9d, R10d, R11d, R12d, R13d, R14d, R15d,
    R16d, R17d, R18d, R19d, R20d, R21d, R22d, R23d,
    R24d, R25d, R26d, R27d, R28d, R29d, R30d, R31d,

    /* 16-bit GPRs */
    Ax, Cx, Dx, Bx, Sp, Bp, Si, Di,
    R8w, R9w, R10w, R11w, R12w, R13w, R14w, R15w,
    R16w, R17w, R18w, R19w, R20w, R21w, R22w, R23w,
    R24w, R25w, R26w, R27w, R28w, R29w, R30w, R31w,

    /* 8-bit GPRs */
    Al, Cl, Dl, Bl, Spl, Bpl, Sil, Dil,
    R8b, R9b, R10b, R11b, R12b, R13b, R14b, R15b,
    R16b, R17b, R18b, R19b, R20b, R21b, R22b, R23b,
    R24b, R25b, R26b, R27b, R28b, R29b, R30b, R31b,
    Ah, Ch, Dh, Bh,

    /* Segment Registers */
    Es, Cs, Ss, Ds, Fs, Gs,

    /* Instruction Pointer */
    Rip, Eip, Ip,

    /* Vector Registers (XMM/YMM/ZMM) */
    Xmm0, Xmm1, Xmm2, Xmm3, Xmm4, Xmm5, Xmm6, Xmm7,
    Xmm8, Xmm9, Xmm10, Xmm11, Xmm12, Xmm13, Xmm14, Xmm15,
    Xmm16, Xmm17, Xmm18, Xmm19, Xmm20, Xmm21, Xmm22, Xmm23,
    Xmm24, Xmm25, Xmm26, Xmm27, Xmm28, Xmm29, Xmm30, Xmm31,
    Ymm0, Ymm1, Ymm2, Ymm3, Ymm4, Ymm5, Ymm6, Ymm7,
    Ymm8, Ymm9, Ymm10, Ymm11, Ymm12, Ymm13, Ymm14, Ymm15,
    Ymm16, Ymm17, Ymm18, Ymm19, Ymm20, Ymm21, Ymm22, Ymm23,
    Ymm24, Ymm25, Ymm26, Ymm27, Ymm28, Ymm29, Ymm30, Ymm31,
    Zmm0, Zmm1, Zmm2, Zmm3, Zmm4, Zmm5, Zmm6, Zmm7,
    Zmm8, Zmm9, Zmm10, Zmm11, Zmm12, Zmm13, Zmm14, Zmm15,
    Zmm16, Zmm17, Zmm18, Zmm19, Zmm20, Zmm21, Zmm22, Zmm23,
    Zmm24, Zmm25, Zmm26, Zmm27, Zmm28, Zmm29, Zmm30, Zmm31,

    /* AMX Tile Registers */
    Tmm0, Tmm1, Tmm2, Tmm3, Tmm4, Tmm5, Tmm6, Tmm7,

    /* x87 FPU Registers */
    St0, St1, St2, St3, St4, St5, St6, St7,

    /* Control Registers */
    Cr0, Cr1, Cr2, Cr3, Cr4, Cr5, Cr6, Cr7,
    Cr8, Cr9, Cr10, Cr11, Cr12, Cr13, Cr14, Cr15,

    /* Debug Registers */
    Dr0, Dr1, Dr2, Dr3, Dr4, Dr5, Dr6, Dr7,
    Dr8, Dr9, Dr10, Dr11, Dr12, Dr13, Dr14, Dr15,

    /* Mask Registers (AVX-512) */
    K0, K1, K2, K3, K4, K5, K6, K7,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OperandSize {
    Size8,
    Size16,
    Size32,
    Size64,
    Size128,
    Size256,
    Size512,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Immediate {
    U8(u8),
    U16(u16),
    U32(u32),
    U64(u64),
    I8(i8),
    I16(i16),
    I32(i32),
    I64(i64),
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MemoryAccess {
    pub segment: Option<Segment>,
    pub base: Option<Register>,
    pub index: Option<Register>,
    pub scale: u8,
    pub displacement: i64,
    pub size: u8,
    /* AVX-512 Broadcast semantics. True if reading a single element and broadcasting it to the vector. */
    pub broadcast: bool,
    /* Calculated absolute address for RIP-relative memory addressing. */
    pub absolute_address: Option<u64>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Segment {
    CS, DS, ES, FS, GS, SS,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InstructionMetadata {
    pub length: u8,
    pub architecture: Architecture,
    pub category: InstructionCategory,
    pub extension: IsaExtension,
    pub control_flow: ControlFlow,
    pub flags: FlagEffect,
    pub attributes: Attributes,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IsaExtension {
    Base,
    SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2,
    AVX, AVX2, AVX512,
    AmxTile, AmxInt8, AmxBf16,
    BMI1, BMI2,
    AES, PCLMULQDQ,
    APX, XOP, TSX, CET,
}

/*
** Instruction attributes provide high-level properties of the instruction
** that are useful for static analysis without inspecting the operands.
*/
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct Attributes {
    pub is_stack_op: bool,
    pub is_string_op: bool,
    pub is_vector_op: bool,
    pub is_privileged: bool,
    pub is_far_branch: bool,
    pub has_lock: bool,
    pub has_rep: bool,
    pub has_repne: bool,
    pub has_xacquire: bool,
    pub has_xrelease: bool,
    pub sae: bool,
    pub rounding_mode: Option<RoundingMode>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RoundingMode {
    RoundNearest,
    RoundDown,
    RoundUp,
    RoundZero,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct FlagEffect {
    /* Flags that are read/tested by the instruction. */
    pub tested: u32,
    /* Flags whose value is calculated/modified by the instruction. */
    pub modified: u32,
    /* Flags that are always set to 1. */
    pub set: u32,
    /* Flags that are always cleared to 0. */
    pub cleared: u32,
    /* Flags whose state is undefined after execution. */
    pub undefined: u32,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ControlFlow {
    None,
    ConditionalBranch,
    UnconditionalBranch,
    Call,
    Return,
    Interrupt,
    Syscall,
}

/*
** Bitmask for CPU status flags (EFLAGS/RFLAGS).
*/
pub mod flags {
    pub const CF: u32 = 1 << 0;  // Carry Flag
    pub const PF: u32 = 1 << 2;  // Parity Flag
    pub const AF: u32 = 1 << 4;  // Auxiliary Carry Flag
    pub const ZF: u32 = 1 << 6;  // Zero Flag
    pub const SF: u32 = 1 << 7;  // Sign Flag
    pub const TF: u32 = 1 << 8;  // Trap Flag
    pub const IF: u32 = 1 << 9;  // Interrupt Enable Flag
    pub const DF: u32 = 1 << 10; // Direction Flag
    pub const OF: u32 = 1 << 11; // Overflow Flag
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Architecture {
    X86,
    X64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InstructionCategory {
    Arithmetic,
    DataTransfer,
    ControlFlow,
    System,
    Miscellaneous,
}
