import urllib.request
import xml.etree.ElementTree as ET
import os

OPCODES_XML_URL = "https://raw.githubusercontent.com/golang/arch/master/x86/x86.csv"
OUTPUT_FILE = "../src/autogen_isa.rs"

def main():
    print(f"[*] Downloading x86-64 XML Database from {OPCODES_XML_URL}...")
    
    # In a real build pipeline, you'd cache this locally.
    req = urllib.request.Request(OPCODES_XML_URL, headers={'User-Agent': 'Mozilla/5.0'})
    with urllib.request.urlopen(req) as response:
        xml_data = response.read()

    print("[*] Parsing CSV data...")
    mnemonics = set()
    opcode_map_1byte = {} # Maps primary opcode byte -> Mnemonic string
    opcode_map_0f = {}    # Maps 0x0F map opcodes -> Mnemonic string
    
    import csv
    import io
    import re
    
    decoded = xml_data.decode('utf-8')
    reader = csv.reader(io.StringIO(decoded))
    
    for row in reader:
        if not row or row[0].startswith('#'):
            continue
        
        name = row[0]
        enc = row[1]
        
        # Standardize mnemonic to CamelCase for Rust Enums
        mnemonic_rust = name.lower().capitalize()
        mnemonic_rust = ''.join(e for e in mnemonic_rust if e.isalnum())
        if mnemonic_rust:
            mnemonics.add(mnemonic_rust)
            
        parts = enc.split()
        
        # Extract opcodes
        try:
            # Strip prefixes like REX, VEX, EVEX
            clean_parts = [p for p in parts if not (p.startswith('REX') or p.startswith('VEX') or p.startswith('EVEX'))]
            
            if len(clean_parts) >= 2 and clean_parts[0] == '0F':
                op = int(clean_parts[1], 16)
                if op not in opcode_map_0f:
                    opcode_map_0f[op] = mnemonic_rust
            elif len(clean_parts) >= 1:
                if all(c in '0123456789ABCDEFabcdef' for c in clean_parts[0]) and len(clean_parts[0]) == 2:
                    op = int(clean_parts[0], 16)
                    if op not in opcode_map_1byte:
                        opcode_map_1byte[op] = mnemonic_rust
        except Exception:
            pass

    mnemonics = sorted(list(mnemonics))
    
    print(f"[*] Generating Rust Source Code ({len(mnemonics)} unique mnemonics)...")
    
    # Generate Rust Source
    rust_code = [
        "/*",
        "** AUTO-GENERATED BY scripts/generate_isa.py",
        "** DO NOT EDIT THIS FILE DIRECTLY.",
        "** Database sourced from Go Arch x86.csv.",
        "*/\n",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub enum AutoMnemonic {"
    ]
    
    for m in mnemonics:
        rust_code.append(f"    {m},")
    rust_code.append("    Unknown,")
    rust_code.append("}\n")
    
    rust_code.append("impl AutoMnemonic {")
    rust_code.append("    pub fn as_str(&self) -> &'static str {")
    rust_code.append("        match self {")
    for m in mnemonics:
        rust_code.append(f'            AutoMnemonic::{m} => "{m.lower()}",')
    rust_code.append('            AutoMnemonic::Unknown => "??",')
    rust_code.append("        }")
    rust_code.append("    }")
    rust_code.append("}\n")

    rust_code.append("\n// AUTO-GENERATED: resolve_opcode template for 1-byte opcodes")
    rust_code.append("pub fn auto_resolve_opcode(opcode: u8) -> AutoMnemonic {")
    rust_code.append("    match opcode {")
    
    for op in sorted(opcode_map_1byte.keys()):
        m = opcode_map_1byte[op]
        rust_code.append(f"        0x{op:02X} => AutoMnemonic::{m},")
        
    rust_code.append("        _ => AutoMnemonic::Unknown,")
    rust_code.append("    }")
    rust_code.append("}")
    
    rust_code.append("\n// AUTO-GENERATED: resolve_opcode template for 0x0F map")
    rust_code.append("pub fn auto_resolve_opcode_0f(opcode: u8) -> AutoMnemonic {")
    rust_code.append("    match opcode {")
    
    for op in sorted(opcode_map_0f.keys()):
        m = opcode_map_0f[op]
        rust_code.append(f"        0x{op:02X} => AutoMnemonic::{m},")
        
    rust_code.append("        _ => AutoMnemonic::Unknown,")
    rust_code.append("    }")
    rust_code.append("}")
    
    rust_code.append("\n// AUTO-GENERATED: flag effects template")
    rust_code.append("pub fn auto_flag_effects(mnemonic: AutoMnemonic) -> u32 {")
    rust_code.append("    match mnemonic {")
    rust_code.append("        AutoMnemonic::Unknown => 0,")
    rust_code.append("        _ => 1,")
    rust_code.append("    }")
    rust_code.append("}")

    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    with open(OUTPUT_FILE, "w") as f:
        f.write("\n".join(rust_code))
        
    print(f"[+] Successfully generated {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
